version: "3"

services:
  spotify-server:
    build: .
    restart: always
    volumes:
      - ./data:/data:rw
    ports:
      - 8096:8096
    environment:
      - SERVER_MODE=release
    env_file:
      - .env